# Docker Compose Configuration
# visit https://docs.docker.com/compose/


version: '3.8'
services:
  # app service for your backend
  app:
    container_name: backend_API
    image: jerry2311x/nestjs-backend-api-test
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    environment:
      DATABASE_NAME : DATABASE_USERS_TEST_2
      # DATABASE_USER : admin
      # DATABASE_PASS : admin
      DATABASE_URI : mongodb://host.docker.internal:27017/users_test_2
      
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin